arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
#synthetic-package: false # that shit messed up
#output-dir: lib/l10n/generated
#output-class: S
#untranslated-messages-file: l10n_errors.txt
